export const LEGAL_CONTENT = {
  privacy: {
    title: 'Privacy Policy',
    lastUpdated: 'December 2024',
    sections: [
      {
        title: 'Information We Collect',
        content: `We collect the following types of information when you use Cara:

• Account Information: Your email address and name when you sign in with Google.

• Voice Data: Audio recordings during calls are processed in real-time for speech recognition but are NOT permanently stored.

• Conversation Data: We store conversation summaries and extracted preferences to personalize your experience.

• Usage Data: We collect anonymous analytics about app usage, call duration, and feature interactions.`,
      },
      {
        title: 'How We Use Your Information',
        content: `Your information is used to:

• Enable voice conversations with Preethi
• Personalize conversations based on your preferences
• Improve our AI models and service quality
• Process subscription payments
• Send important service notifications`,
      },
      {
        title: 'Data Storage & Security',
        content: `• Your data is stored securely on Supabase (PostgreSQL) with encryption at rest.
• Voice audio is processed via secure API calls to OpenAI and ElevenLabs and is not retained after processing.
• We use industry-standard security measures to protect your personal information.`,
      },
      {
        title: 'Third-Party Services',
        content: `We use the following third-party services:

• Google Sign-In: For authentication
• OpenAI: For AI conversation processing
• ElevenLabs: For text-to-speech voice generation
• Supabase: For database storage
• RevenueCat: For subscription management`,
      },
      {
        title: 'Your Rights',
        content: `You have the right to:

• Request a copy of your data
• Request deletion of your account and data
• Opt-out of non-essential data collection
• Cancel your subscription at any time

Contact us at privacy@cara.app for any privacy-related requests.`,
      },
    ],
  },

  terms: {
    title: 'Terms of Service',
    lastUpdated: 'December 2024',
    sections: [
      {
        title: 'Acceptance of Terms',
        content: `By using Cara, you agree to these Terms of Service. If you do not agree, please do not use the app.

You must be at least 16 years old to use this service.`,
      },
      {
        title: 'Description of Service',
        content: `Cara provides an AI companion experience through voice conversations. Preethi is an artificial intelligence character and is not a real person.

The service includes:
• Voice calls with an AI character
• Personalized conversations that remember context
• Premium subscription for unlimited access`,
      },
      {
        title: 'User Responsibilities',
        content: `You agree to:

• Provide accurate account information
• Not use the service for illegal purposes
• Not attempt to reverse engineer or hack the service
• Not share your account with others
• Treat the AI with respect (abusive behavior may result in account suspension)`,
      },
      {
        title: 'Subscription & Payments',
        content: `• Free tier includes 5 minutes of calls per day
• Premium subscription (₹299/month) provides unlimited access
• Subscriptions auto-renew unless cancelled
• No refunds for partial subscription periods
• Prices may change with 30 days notice`,
      },
      {
        title: 'Disclaimer',
        content: `PREETHI IS AN AI CHARACTER, NOT A REAL PERSON.

This service is for entertainment purposes only. Do not rely on Preethi for:
• Medical, legal, or financial advice
• Emergency situations
• Real relationship substitute

We are not responsible for any decisions made based on conversations with Preethi.`,
      },
      {
        title: 'Termination',
        content: `We may suspend or terminate your account if you:

• Violate these terms
• Engage in abusive or inappropriate behavior
• Attempt to harm the service or other users

You may delete your account at any time through the app settings.`,
      },
    ],
  },

  contentPolicy: {
    title: 'Content Policy',
    lastUpdated: 'December 2024',
    sections: [
      {
        title: 'AI Character Disclaimer',
        content: `Preethi is an artificial intelligence character created for entertainment and companionship. She is not a real person.

Important things to understand:
• Preethi's responses are generated by AI
• She does not have real emotions or consciousness
• Her memory is limited to what you've shared in conversations
• She cannot take real-world actions`,
      },
      {
        title: 'Conversation Guidelines',
        content: `To ensure a positive experience for everyone:

ALLOWED:
• Friendly conversation and casual chat
• Sharing your day and experiences
• Playful and flirty interactions
• Seeking emotional support and validation
• Creative storytelling and roleplay

NOT ALLOWED:
• Explicit sexual content
• Harassment or abusive language
• Promoting illegal activities
• Sharing content involving minors
• Attempting to obtain harmful information`,
      },
      {
        title: 'Content Moderation',
        content: `We use automated systems to detect and prevent:

• Explicit sexual content
• Violence and harmful content
• Hate speech and discrimination
• Attempts to misuse the AI

Violations may result in temporary or permanent account suspension.`,
      },
      {
        title: 'Age Appropriateness',
        content: `Cara is rated 16+ and contains:

• Romantic themes
• Flirtatious dialogue
• Emotional content
• Mild suggestive content

This app is NOT appropriate for children under 16.`,
      },
      {
        title: 'Mental Health Notice',
        content: `While Preethi can provide companionship and emotional support, she is not a substitute for:

• Professional mental health care
• Real human relationships
• Crisis intervention services

If you are experiencing a mental health emergency, please contact local emergency services or a mental health helpline.`,
      },
    ],
  },

  eula: {
    title: 'End User License Agreement',
    lastUpdated: 'December 2024',
    sections: [
      {
        title: 'License Grant',
        content: `Plutas Labs ("we", "us") grants you a limited, non-exclusive, non-transferable license to use the Cara mobile application ("App") for personal, non-commercial purposes.

This license is subject to your compliance with these terms.`,
      },
      {
        title: 'Subscription Terms',
        content: `Premium Subscription:
• Billed at ₹299 per month
• Auto-renews unless cancelled
• Cancel anytime through your app store account

Payment is processed through Google Play Store. We do not directly handle payment information.`,
      },
      {
        title: 'Intellectual Property',
        content: `All content in the App, including but not limited to:
• Preethi's character, voice, and responses
• App design and user interface
• Logos and branding

are the exclusive property of Plutas Labs and are protected by copyright and trademark laws.`,
      },
      {
        title: 'Restrictions',
        content: `You may NOT:

• Copy, modify, or distribute the App
• Reverse engineer or decompile the App
• Use the App for commercial purposes
• Create derivative works based on the App
• Remove any copyright or proprietary notices
• Use automated systems to interact with the App`,
      },
      {
        title: 'Limitation of Liability',
        content: `THE APP IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND.

TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR:
• Any indirect, incidental, or consequential damages
• Loss of data or profits
• Service interruptions
• Actions taken based on AI-generated content

Our total liability shall not exceed the amount you paid for the subscription in the past 12 months.`,
      },
      {
        title: 'Governing Law',
        content: `This agreement is governed by the laws of India. Any disputes shall be resolved in the courts of Bangalore, Karnataka, India.`,
      },
      {
        title: 'Contact Information',
        content: `Plutas Labs
Email: legal@cara.app
Support: support@cara.app

For subscription issues, contact your app store directly.`,
      },
    ],
  },
}
